### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted[BUG] 

### ISSUE THREAD

**Issue by CristianSavin** [surfstudio/flutter-otp-autofill#54]
The otp_autofill: 2.1.0 (latest) version, cause the crash on some Android devices. You can view the full error message bellow. The error is collected from the FirebaseCrashlytics.

Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at ru.surfstudio.otp_autofill.OTPPlugin.onActivityResult(OTPPlugin.java:23)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:13)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:10)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:5)
       at android.app.Activity.dispatchActivityResult(Activity.java:7743)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4744)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4793)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

**Comment by plasticfiresam** [comment]
@CristianSavin Could you provide more information about devices on which crash occure, and provide us with minimal code which can reproduce this issue?
