### ISSUE TITLE
[crash]  com.google.android.gms.common.api.ApiException: 16

### ISSUE THREAD

**Issue by liubowen-ola** [surfstudio/flutter-otp-autofill#68]
The otp_autofill:3.0.0 (latest) version, cause the crash on some Android devices. 

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {sg.partying.android.lite/com.imbb.banban.android.MainActivity}: com.google.android.gms.common.api.ApiException: 16: 
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4458)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4500)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Caused by com.google.android.gms.common.api.ApiException: 16: 
       at com.google.android.gms.internal.auth-api.zbay.getPhoneNumberFromIntent(com.google.android.gms:play-services-auth@@20.6.0:4)
       at ru.surfstudio.otp_autofill.OTPPlugin.onActivityResult(OTPPlugin.kt:134)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
       at android.app.Activity.dispatchActivityResult(Activity.java:7598)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4451)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4500)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by EinatK** [comment]
Will this be resolved? Package is unusable

**Comment by No1Ks** [comment]
3.0.2 contains this bug too

**Comment by romreed** [comment]
@No1Ks Hi
check please fix 
add your your pubspec.yaml
```
  otp_autofill:
    git:
      url: https://github.com/BPCdb/flutter-otp-autofill
```

**Comment by No1Ks** [comment]
> @No1Ks Hi check please fix add to your pubspec.yaml
> 
> ```
>   otp_autofill:
>     git:
>       url: https://github.com/BPCdb/flutter-otp-autofill
> ```

404

**Comment by romreed** [comment]
> > @No1Ks Hi check please fix add to your pubspec.yaml
> > ```
> >   otp_autofill:
> >     git:
> >       url: https://github.com/BPCdb/flutter-otp-autofill
> > ```
> 
> 404
 New url https://github.com/romreed/flutter-otp-autofill

**Comment by No1Ks** [comment]
> > > @No1Ks Hi check please fix add to your pubspec.yaml
> > > ```
> > >   otp_autofill:
> > >     git:
> > >       url: https://github.com/BPCdb/flutter-otp-autofill
> > > ```
> > 
> > 
> > 404
> > @No1Ks New url https://github.com/romreed/flutter-otp-autofill

Thank you) ll check tomorrow!
