### ISSUE TITLE
[BUG] live app get firebase_auth sms received app close.

### ISSUE THREAD

**Issue by Bhautik2103** [surfstudio/flutter-otp-autofill#77]
D/AndroidRuntime(26115): Shutting down VM
E/AndroidRuntime(26115): FATAL EXCEPTION: main
E/AndroidRuntime(26115): Process: com.cubicshoes, PID: 26115
E/AndroidRuntime(26115): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.cubicshoes (has extras) } in com.google.android.gms.internal.firebase-auth-api.zzadx@97f0599
E/AndroidRuntime(26115): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1980)
E/AndroidRuntime(26115): 	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
E/AndroidRuntime(26115): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(26115): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(26115): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26115): 	at android.os.Looper.loopOnce(Looper.java:257)
E/AndroidRuntime(26115): 	at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(26115): 	at android.app.ActivityThread.main(ActivityThread.java:8825)
E/AndroidRuntime(26115): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26115): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(26115): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(26115): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(26115): 	at java.util.regex.Matcher.reset(Matcher.java:386)
E/AndroidRuntime(26115): 	at java.util.regex.Matcher.<init>(Matcher.java:210)
E/AndroidRuntime(26115): 	at java.util.regex.Pattern.matcher(Pattern.java:989)
E/AndroidRuntime(26115): 	at com.google.android.gms.internal.firebase-auth-api.zzadt.zza(com.google.firebase:firebase-auth@@22.3.1:3)
E/AndroidRuntime(26115): 	at com.google.android.gms.internal.firebase-auth-api.zzadx.onReceive(com.google.firebase:firebase-auth@@22.3.1:13)
E/AndroidRuntime(26115): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1943)
E/AndroidRuntime(26115): 	... 10 more
I/Process (26115): Sending signal. PID: 26115 SIG: 9
Lost connection to device.

**Comment by DmitrDomrachev** [comment]
@Bhautik2103 Could you provide us with minimal code which can reproduce this issue?
